sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
        acl_user_manager: fos_user.user_manager # Name of the user manager service used to retrieve ACL users

    options:
        html5_validate: false # does not use html5 validation
        confirm_exit:   false # disable confirmation when quitting with unsaved changes
        use_select2:    false # disable select2
        pager_links:    5     # pager max links to display

    # set to true to persist filter settings per admin module in the user's session
    persist_filters: false