parameters:
#    stikair_init.example.class: Stikair\Bundle\InitBundle\Example

services:
#    stikair_init.example:
#        class: %stikair_init.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
